### ISSUE TITLE
Websites think I have no flash installed

### ISSUE THREAD

**Issue by Diskutant** [infernoboy/JavaScript-Blocker-5#1]
Since I updated from JavaScript Blocker 4 to 5 websites that need flash just show an error that I have no flash installed. 
Is there an option that would let websites see my flash plugin again?

An example would be http://www.speedtest.net/

**Comment by infernoboy** [comment]
Are you using the feature "Randomize environmental information"? If so, that would be why websites cannot detect if you have flash installed.

**Comment by Diskutant** [comment]
Thanks, that did the trick! :)
