### ISSUE TITLE
GM_deleteValue not deleting values

### ISSUE THREAD

**Issue by ccd0** [infernoboy/JavaScript-Blocker-5#11]
Using:
JS Blocker 5 5.1.0
Safari 9.1.1 (10601.6.17)

Test script:
```
// ==UserScript==
// @name Test
// @namespace RCjQiTmr2bWFPcR-5.1.0-160420
// @include http://www.example.com/
// @grant GM_getValue
// @grant GM_setValue
// @grant GM_deleteValue
// ==/UserScript==

alert([1, GM_getValue("key", "not set")]);
GM_setValue("key", "value");
alert([2, GM_getValue("key", "not set")]);
GM_deleteValue("key");
alert([3, GM_getValue("key", "not set")]);
```
This should show the alerts
`1,not set`
`2,value`
`3,not set`
but with JS Blocker it shows
`1,not set`
`2,value`
`3,value`
on the first run and
`1,value`
`2,value`
`3,value`
thereafter.

**Comment by infernoboy** [comment]
I somehow forgot to add the `removeItem` method to `Commands.injected.userScript.storage`; debug mode shows that the command doesn't even exist! Will be fixed in 5.1.2.
