### ISSUE TITLE
Infinite refresh loop on Safari Technology Preview Release 13

### ISSUE THREAD

**Issue by hallabro** [infernoboy/JavaScript-Blocker-5#14]
I'm having an issue running JS Blocker with the latest release of Safari Technology Preview version 13.

When activating the extension the current page keeps reloading infinitely. I have tried multiple websites and they all behave the same way.

Maybe a gif can explain it better than I can put in words: [giphy](https://media.giphy.com/media/l0HlSdRoIju3XV4CQ/giphy.gif)

According to the console the error can be found on line 4668 of `compiled.js` which I think corresponds to line 21 of [js/infected/blocker.js](https://github.com/infernoboy/JavaScript-Blocker-5/blob/cb30ef86a60c4094b6b802c8f0179d25ed9f8be9/js/injected/blocker.js#L21):

```javascript
throw new Error('...');
```

**Comment by infernoboy** [comment]
It looks like Safari is being a little to cautious. The actual error is:

**SecurityError (DOM Exception 18): Blocked a frame with origin "safari-extension://com.toggleable.javascriptblocker5-6s8j5hv3h4" from accessing a frame with origin "null".  The frame requesting access has a protocol of "safari-extension", the frame being accessed has a protocol of "". Protocols must match.**

I'm not even sure if this can be fixed on my end. It could be a bug in in the latest release of Safari that'll get fixed, I'll just have to report it and see.

**Comment by hallabro** [comment]
Thank you for the swift response. I will wait out a few more preview releases and hope they fix it.

**Comment by infernoboy** [comment]
I managed to "fix" it by just delaying the global page from accessing the popover before it is loaded. I'm not sure what changed in preview 13; maybe it isn't loaded synchronously anymore, or it loads slower? I don't know. Either way, version 5.1.4 works in preview 13.

**Comment by hallabro** [comment]
I can't really tell from the release notes, seems like another undocumented change (I remember a similar issue with 1Password a few months ago).

I downloaded 5.1.4 and it seems to work great, thank you!
