### ISSUE TITLE
Lag in UI

### ISSUE THREAD

**Issue by flouque** [infernoboy/JavaScript-Blocker-5#15]
Disabling animations make the UI very laggy, apple colorful wheel even appears everytime you try to change panel.
Enabling them and using fast animations works as a temporary workaround though.
It's also very slow to load when you launch the browser as it checks every list update. Wouldn't it be better to make them update one after the other or not exactly when the browser is launched? Something like 1/2 minutes after launch

**Comment by infernoboy** [comment]
The lists being updated on every launch was a bug introduced in 5.1.3 which was resolved in 5.1.4. I'll look into the UI lag issues.

**Comment by flouque** [comment]
The UI lags only for a short period of time after launching safari. This happened on 5.1.3 but it seemed the list updating fix did the trick ad it looks to act better now
Thanks for the quick answer.

**Comment by infernoboy** [comment]
If that was the only lag issue you were noticing, I'm going to close this issue.
