### ISSUE TITLE
Silently blocking canvas fingerprints

### ISSUE THREAD

**Issue by rraallvv** [infernoboy/JavaScript-Blocker-5#16]
I am not tracking how many times show the canvas finger printing block pop-up, but  this is starting to annoy me. Maybe 2 or 3 sites out of 10 are showing this pop-up. Is there any option to silently block those trackers without showing up any pop-up.

Keep up the good work.

**Comment by infernoboy** [comment]
You can change the settings from Settings > Other > Canvas fingerprinting protection.
