### ISSUE TITLE
"Block scripts from different domains" seems not to allow scripts from same domain

### ISSUE THREAD

**Issue by jsit** [infernoboy/JavaScript-Blocker-5#18]
Maybe I've just got something configured incorrectly, but on www.sanebox.com, I had to manually allow a script from assets.sanebox.com, even though "Block scripts from different domains" is selected. Shouldn't scripts from assets.* be allowed on www.* in that case?

Similarly, assets-cdn.github.com had to be manually allowed on this page.

JS Blocker 5.1.6 (170109)
Safari 10.0.2 (11602.3.12.0.1)

**Comment by infernoboy** [comment]
It does appear to be backwards… "Different domains" seems to be doing what "Different hostnames" should be doing and vice versa. I suppose I'll have to swap what those do.

**Comment by jsit** [comment]
Ah!, that's it. I changed it to "different hostnames" and it's working now. Thanks!

**Comment by infernoboy** [comment]
The setting will be corrected in the next release. The update process will take care of switching it back to "Different domains". Thanks for letting me know about this.
