### ISSUE TITLE
JS Blocker is blocking things, even though it shouldn't

### ISSUE THREAD

**Issue by rbieb** [infernoboy/JavaScript-Blocker-5#19]
Website I'm using is www.golem.de

My settings:
- All filter lists disabled
- "Ignore built-in filtering rules" is activated
- Script blocker is activated
- Script blocker is set to block from "filter lists only"

On www.golem.de, the scripts for www.golem.de are being blocked by the script blocker, even though I have both the built-in rules and all filter lists deactivated. So why is anything being blocked?

edit: Different example
www.youtube.com

Script blocker is set to only block scripts from different domains, yet it doesn't allow scripts from www.youtube.com on www.youtube.com?

**Comment by infernoboy** [comment]
I'm not seeing any issues here with scripts being blocked when they shouldn't. Could you provide a copy of your settings via Menu > Submit Feedback so that I can verify your setup is correct for what you want to accomplish?

As for the youtube.com issue, that is a bug in the current release that I've already fixed in #18. For now, switch it to "Different hostnames", which actually has the effect of "Different domains".

**Comment by rbieb** [comment]
I've switched everything to "different hostnames", but without success. youtube.com scripts are still being blocked.

I'll happily submit feedback, but clicking "submit feedback" just shows an empty window. Do I need to send it to a special email adress?

**Comment by infernoboy** [comment]
![screen shot 2017-02-08 at 8 50 59 am](https://cloud.githubusercontent.com/assets/25857/22739916/b986e00a-eddb-11e6-89ff-d687240c8b62.png)
What do you mean by a an empty window? You should be seeing that, just click Submit.

**Comment by rbieb** [comment]
Just sent it. My problem was that your email address was missing.

**Comment by infernoboy** [comment]
The email address field is for your email address so that I can reply! Sorry if that wasn't obvious, i'll make that clearer. I got your feedback and will look at it when I get a chlance.

**Comment by rbieb** [comment]
Ah, now I get it 👍

Thank you. I hope those are the correct settings, if they aren't, I'll send you another feedback.

**Comment by infernoboy** [comment]
The settings you sent me has "Ignore built-in filtering rules" unchecked.

Other than that, it is working as expected:

![screen shot 2017-02-08 at 12 59 52 pm](https://cloud.githubusercontent.com/assets/25857/22750356/7f74d4a8-edfe-11e6-9013-e827231cc2e4.png)

Nothing from www.golem.de was blocked. Is there a background color on the blocked items you are referring to?

**Comment by rbieb** [comment]
Something is off here, this is what it looks like for me:

![golem](https://cloud.githubusercontent.com/assets/6862450/22776419/dc0188d6-eeaf-11e6-98b3-4b7553840ec6.png)

I've also sent you another report.

**Comment by infernoboy** [comment]
The yellow indicates that it's a "Trust" rule, but you don't even have that enabled. That is strange. Disabling "Unknown Websites" is supposed to clear the trust, but JSB is still processing it. I'll have to make it so the trust list isn't evaluated at all if disabled.
