### ISSUE TITLE
Rules for an IP address are not saved

### ISSUE THREAD

**Issue by vnebelung** [infernoboy/JavaScript-Blocker-5#2]
When you create a rule for a website identified through its IP address the created rule is never saved, regardless whether you have chosen temporarily or always.

**Comment by infernoboy** [comment]
JSB should work just fine with IP addresses. They'd be referred to as "domains", though. I haven't encountered any issues with allowing/blocking on IP-based websites. If you could please provide a copy of your settings (click the Settings arrow, then Backup and uncheck everything but Settings) it would be greatly appreciated and would help me debug this issue.

**Comment by vnebelung** [comment]
I must correct the bug description:
The rules are saved, but not applied to the site. It happens with all sites that have an IP address in the URL bar. As soon as the site is accessed through its domain name the rules are applied as they should.

I noticed one thing: In the Rules tab the rules are listed with a dot before the ip address: ".10.0.0.1". Is this intended?

Here you go:
> {"Storage-StoreSettings":{"STORE":{"enabledKinds":{"accessed":-1,"value":{"STORE":{"frame":{"accessed":-1,"value":false},"embed":{"accessed":-1,"value":false},"xhr":{"accessed":-1,"value":false}},"props":{}}},"lockerAlwaysLocked":{"accessed":-1,"value":{"STORE":{"clearRules":{"accessed":-1,"value":false},"importBackupSettings":{"accessed":-1,"value":false}},"props":{}}},"alwaysBlock":{"accessed":-1,"value":{"STORE":{"script":{"accessed":-1,"value":"everywhere"},"frame":{"accessed":-1,"value":"everywhere"},"xhr":{"accessed":-1,"value":"ask"},"embed":{"accessed":-1,"value":"everywhere"}},"props":{}}},"enabledSpecials":{"accessed":-1,"value":{"STORE":{"contextmenu_overrides":{"accessed":-1,"value":true},"window_resize":{"accessed":-1,"value":true},"autocomplete_disabler":{"accessed":-1,"value":true},"canvas_data_url":{"accessed":-1,"value":"4"},"anchor_titles":{"accessed":-1,"value":true},"simple_referrer":{"accessed":-1,"value":false},"inline_script_execution":{"accessed":-1,"value":true}},"props":{}}}},"props":{}},"debugMode":false,"showHiddenItems":true,"showExpanderLabels":false,"settingCurrentView":"#setting-views-rules","temporarilyShowResourceURLs":false,"showUnblockedScripts":false,"largeFont":false,"useLocker":false,"disableTime":300000,"popoverHeightExpanded":451,"trialStart":-1,"useSimplePageEditor":true,"installedBundle":150602,"showPageEditorImmediately":true,"showItemDescription":true,"toolbarDisplay":"blocked","lastRuleWasTemporary":true,"autoSnapshots":false,"defaultRuleList":"temporary","defaultRuleDomain":"domain","showResourceURLs":false,"popoverHeight":401,"pageHostColumnAllowedWidth":0.5,"showBlockFirstVisitNotification":false,"blockFirstVisit":"host","createRulesOnClose":true,"installID":"bkaiPEzJN0PLg32-5.0.2-150425","popoverWidth":515,"openSettings":false,"setupComplete":true,"useAnimations":false,"popoverWidthExpanded":601,"darkMode":false,"isDisabled":false}

**Comment by infernoboy** [comment]
Aha! The issue lies in the setting `defaultRuleDomain: "domain"`. In the UI this is "Create rules that apply to: Website domain". I'll be sure to fix this to work with IP addresses correctly.

**Comment by vnebelung** [comment]
That works, thank you.
