### ISSUE TITLE
Unable to disable JS Blocker for site

### ISSUE THREAD

**Issue by lukf** [infernoboy/JavaScript-Blocker-5#22]
When clicking on “Disable”, whatever site I am on, JS Blocker reloads the page, but doesn’t disable itself. The “Disable” button does not switch to “Enable”.
I am running JS Blocker 5.2.1 in Safari 11.0.

**Comment by infernoboy** [comment]
Not seeing any issues here in 11. Are you using Safari Tech. Preview 11 or Safari 11 on High Sierra?

**Comment by lukf** [comment]
Just resolved the issue by reinstalling JS Blocker. I'm running Safari 11 (13604.1.38.1.6) on High Sierra (17A362a), but can't reproduce the problem now after reconstructing my JS Blocker configuration. I'll let you know if it comes back.
