### ISSUE TITLE
Option to disable for all subdomains

### ISSUE THREAD

**Issue by maia** [infernoboy/JavaScript-Blocker-5#26]
I'd like to suggest an option to disable JS Blocker for all subdomains, as some websites use multiple (and rotating) subdomains for their content (e.g. when holding command or alt the "disable" button would change it's name to "disable for all subdomains"). 

Ideally there'd also be a UI where all disabled domains are listed, with a checkbox next to each domain if it's extended to all subdomains of the given domain.

**Comment by infernoboy** [comment]
I really don't want to do that extensive of a UI update, for version 5 at least. For now, you can click the downward arrow on the Edit button, click Disable JS Blocker…, then change the "on sub.example.com" to "within example.com". It will create a rule that begins with a ".". You can easily see these sub-domain rules from the rules UI by changing the "sort by" to Priority ^ (ascending).
