### ISSUE TITLE
Gmail js blocked

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [infernoboy/JavaScript-Blocker-5#27]
Two days ago I tried to log into Gmail and was taken to a page with two buttons and it asked if I wanted to use HTML (basic) mail or  "the latest (standard) Gmail."

I wound up in an endless loop of clicking "latest" and the page just refreshed - I was never able to log in. I tried several accounts and all were the same.

A few minutes ago I tried again and chose HTML and was able to log in to basic mail.
And at the top of the page is a banner which says **"You have been redirected to the basic HTML version because this browser is not supported. To use standard view please upgrade to a supported browser."**

Well, Safari _is_ one of the supported browsers listed, so I thought it might be an extension issue.

JS Blocker didn’t show any blocked items, it says **Blocked 0 hosts**.
The only blocked item is "Always allow autocomplete."

Then I disabled JS and voilá! I was able to switch to standard Gmail.

So, why is JS blocking something on Gmail even though it says it isn’t?
That’s obviously an important site used by millions.

And instead of starting another thread I have another question:
I noticed that sometimes the same item (with the same url) is listed under allowed _and_ blocked.
How can it be both?

One place I noticed that yesterday is http://springfieldnews.com.
The site is defunct, but **images.smartname.com** is listed under scripts on both sides.
I noticed the same thing later on another site.

**Comment by infernoboy** [comment]
Could you send me a copy of your settings by opening JSB and clicking Menu > Submit Feedback? I am not seeing any issues with gmail here.

I can't seem to load http://springfieldnews.com, but an item being listed under both sides could be because the entire host isn't blocked, only a specific script. You can switch to URL view to see the exact item being blocked/allowed (open the Page menu via the arrow for how to do this).

**Comment by GitTheHellOutaHere** [comment]
Found another page that won't load unless
      JSB is disabled.
      
      https://www.paintdocs.com/docs/app/web/page/docCategory/
        
        After disabling I see this.
          
          
          After correctly submitting, the site will load.
          
          
        
    On 4/13/18 10:22 AM, Rebel wrote:
    
    
      
      I can log into Gmail but only in basic mode.
      Disable JSB and can switch to standard.
      Re-enable and refresh page and it's back to basic.
      
      
      message: 
      displayVersion: 5.3.0
      bundleID: 180103
      userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6)
      AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1
      Safari/605.1.15
      console: Error Messages
      
      
      
      
      Debug Messages
      
      
      installID: ZS1K0QTe2cFqCQD-5.3.0-180103
      settings:
eyJpbnN0YWxsSUQiOiJaUzFLMFFUZTJjRnFDUUQtNS4zLjAtMTgwMTAzIiwiZGFya01vZGUiOnRydWUsInNldHVwQ29tcGxldGUiOnRydWUsInVzZVNlY3VyZVNldHRpbmdzIjp0cnVlLCJsYXJnZUZvbnQiOnRydWUsInBvcG92ZXJXaWR0aCI6NTE3LCJwb3BvdmVySGVpZ2h0IjoxMDU1LCJzaG93VW5ibG9ja2VkU2NyaXB0cyI6ZmFsc2UsInNob3dIaWRkZW5JdGVtcyI6ZmFsc2UsInNldHRpbmdDdXJyZW50VmlldyI6IiNzZXR0aW5nLXZpZXdzLWdlbmVyYWwiLCJzaG93UmVzb3VyY2VVUkxzIjp0cnVlLCJpc0Rpc2FibGVkIjpmYWxzZSwibGFzdFJ1bGVXYXNUZW1wb3JhcnkiOmZhbHNlfQ==
      
      
      
      
      
      On 4/8/18 1:57 AM, Travis Roman
        [Masked] wrote:
      
      
        
           Preview: Could you send
            me a copy of your settings by opening JSB and 
            This email is forwarded from a MASKED EMAIL you created
            using Blur.
            IF THIS IS SPAM, CLICK HERE TO BLOCK.
            
            Want to shop safely and privately online? Get Blur Premium. 
        
        
        Could you send me a copy of your settings by opening JSB and
          clicking Menu > Submit Feedback? I am not seeing any issues
          with gmail here.
        I can't seem to load http://springfieldnews.com,
          but an item being listed under both sides could be because the
          entire host isn't blocked, only a specific script. You can
          switch to URL view to see the exact item being blocked/allowed
          (open the Page menu via the arrow for how to do this).
        —
          You are receiving this because you authored the thread.
          Reply to this email directly, view it on GitHub, or mute the thread.
        
          
            
            
          
          
        
        {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/infernoboy/JavaScript-Blocker-5","title":"infernoboy/JavaScript-Blocker-5","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/infernoboy/JavaScript-Blocker-5"}},"updates":{"snippets":[{"icon":"PERSON","message":"@infernoboy in #27: Could you send me a copy of your settings by opening JSB and clicking Menu \u003e Submit Feedback? I am not seeing any issues with gmail here.\r\n\r\nI can't seem to load http://springfieldnews.com, but an item being listed under both sides could be because the entire host isn't blocked, only a specific script. You can switch to URL view to see the exact item being blocked/allowed (open the Page menu via the arrow for how to do this)."}],"action":{"name":"View Issue","url":"https://github.com/infernoboy/JavaScript-Blocker-5/issues/27#issuecomment-379533255"}}}

**Comment by infernoboy** [comment]
Both Gmail and that site work as they are intended to with both default and your settings. You must have a rule that is preventing them from working correctly.

**Comment by GitTheHellOutaHere** [comment]
I sent you my rules on
        the 13th as you'd requested, and again
          today.
            
            
          
            message: 
            displayVersion: 5.3.0
            bundleID: 180103
            userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6)
            AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1
            Safari/605.1.15
            console: Error Messages
            
            
            
            
            Debug Messages
            
            
            installID: ZS1K0QTe2cFqCQD-5.3.0-180103
            settings:
eyJpbnN0YWxsSUQiOiJaUzFLMFFUZTJjRnFDUUQtNS4zLjAtMTgwMTAzIiwiZGFya01vZGUiOnRydWUsInNldHVwQ29tcGxldGUiOnRydWUsInVzZVNlY3VyZVNldHRpbmdzIjp0cnVlLCJsYXJnZUZvbnQiOnRydWUsInBvcG92ZXJXaWR0aCI6NTE3LCJwb3BvdmVySGVpZ2h0IjoxMDU1LCJzaG93VW5ibG9ja2VkU2NyaXB0cyI6ZmFsc2UsInNob3dIaWRkZW5JdGVtcyI6ZmFsc2UsInNldHRpbmdDdXJyZW50VmlldyI6IiNzZXR0aW5nLXZpZXdzLWdlbmVyYWwiLCJzaG93UmVzb3VyY2VVUkxzIjp0cnVlLCJpc0Rpc2FibGVkIjpmYWxzZSwibGFzdFJ1bGVXYXNUZW1wb3JhcnkiOmZhbHNlfQ==
            
            
            
          
    On 4/21/18 11:50 AM, Travis Roman
      [Masked] wrote:
    
    
      
      Both Gmail and that site work as they are intended to with both
        default and your settings. You must have a rule that is
        preventing them from working correctly.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/infernoboy/JavaScript-Blocker-5","title":"infernoboy/JavaScript-Blocker-5","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/infernoboy/JavaScript-Blocker-5"}},"updates":{"snippets":[{"icon":"PERSON","message":"@infernoboy in #27: Both Gmail and that site work as they are intended to with both default and your settings. You must have a rule that is preventing them from working correctly. "}],"action":{"name":"View Issue","url":"https://github.com/infernoboy/JavaScript-Blocker-5/issues/27#issuecomment-383319973"}}}</sc
 ript>
</body>
</html>
</html></blockquote>
    <br>
  </body>
</html>

**Comment by infernoboy** [comment]
For privacy reasons, your rules are not included when you export your settings. If you do want to send those, you'll have to create a backup via the Settings menu > Backup and export that.

**Comment by GitTheHellOutaHere** [comment]
I used the "send an email instead" link which
      placed that info inside an email.
      
      I assumed that was what you needed. There's
        no indication that sending an email does not include the anonymous settings and console
        messages.
          
          I'll send 'em following
            this.
        
      
    
    On 4/21/18 5:31 PM, Travis Roman
      [Masked] wrote:
    
    
      
      For privacy reasons, your rules are not included when you
        export your settings. If you do want to send those, you'll have
        to create a backup via the Settings menu > Backup and export
        that.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/infernoboy/JavaScript-Blocker-5","title":"infernoboy/JavaScript-Blocker-5","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/infernoboy/JavaScript-Blocker-5"}},"updates":{"snippets":[{"icon":"PERSON","message":"@infernoboy in #27: For privacy reasons, your rules are not included when you export your settings. If you do want to send those, you'll have to create a backup via the Settings menu \u003e Backup and export that."}],"action":{"name":"View Issue","url":"https://github.com/infernoboy/JavaScript-Blocker-5/issues/27#issuecomment-383343894"}}}

**Comment by GitTheHellOutaHere** [comment]
Oh, evidently submitting
        feedback from the menu doesn't include them either.
      
      I don't see a Backup button anywhere in the
        Settings tabs.
      
      
      
      
    
    On 4/21/18 5:41 PM, Rebel wrote:
    
    
      
      I used the "send an email instead" link
        which placed that info inside an email.
        
        I assumed that was what you needed. There's
          no indication that sending an email does not include the anonymous settings and console
          messages.
            
            I'll send 'em following
              this.
          
        
      
      On 4/21/18 5:31 PM, Travis Roman
        [Masked] wrote:
      
      
        
        For privacy reasons, your rules are not included when you
          export your settings. If you do want to send those, you'll
          have to create a backup via the Settings menu > Backup and
          export that.
        —
          You are receiving this because you authored the thread.
          Reply to this email directly, view it on GitHub, or mute the thread.
        
          
            
            
          
          
        
        {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/infernoboy/JavaScript-Blocker-5","title":"infernoboy/JavaScript-Blocker-5","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/infernoboy/JavaScript-Blocker-5"}},"updates":{"snippets":[{"icon":"PERSON","message":"@infernoboy in #27: For privacy reasons, your rules are not included when you export your settings. If you do want to send those, you'll have to create a backup via the Settings menu \u003e Backup and export that."}],"action":{"name":"View Issue","url":"https://github.com/infernoboy/JavaScript-Blocker-5/issues/27#issuecomment-383343894"}}}

**Comment by infernoboy** [comment]
The Settings menu, not within the tab. Click the dropdown arrow on the Settings tab itself.

**Comment by GitTheHellOutaHere** [comment]
Just found it - gotta hold the Settings
      button down. Attached.
      
      
      
      
    
    On 4/21/18 5:46 PM, Rebel wrote:
    
    
      
      Oh, evidently submitting
          feedback from the menu doesn't include them either.
        
        I don't see a Backup button anywhere in
          the Settings tabs.
        
        
        
        
      
      On 4/21/18 5:41 PM, Rebel wrote:
      
      
        
        I used the "send an email instead" link
          which placed that info inside an email.
          
          I assumed that was what you needed. There's
            no indication that sending an email does not include the anonymous settings and console
            messages.
              
              I'll send 'em following this.
            
          
        
        On 4/21/18 5:31 PM, Travis Roman
          [Masked] wrote:
        
        
          
          For privacy reasons, your rules are not included when you
            export your settings. If you do want to send those, you'll
            have to create a backup via the Settings menu > Backup
            and export that.
          —
            You are receiving this because you authored the thread.
            Reply to this email directly, view it on GitHub, or mute the thread.
          
            
              
              
            
            
          
          {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/infernoboy/JavaScript-Blocker-5","title":"infernoboy/JavaScript-Blocker-5","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/infernoboy/JavaScript-Blocker-5"}},"updates":{"snippets":[{"icon":"PERSON","message":"@infernoboy in #27: For privacy reasons, your rules are not included when you export your settings. If you do want to send those, you'll have to create a backup via the Settings menu \u003e Backup and export that."}],"action":{"name":"View Issue","url":"https://github.com/infernoboy/JavaScript-Blocker-5/issues/27#issuecomment-383343894"}}}

**Comment by GitTheHellOutaHere** [comment]
Another site that's broken. https://pay.instamed.com/mf.rci
          
          Disable, replace the "unresponsive" URL with
              https://pay.instamed.com/mf.rci and reload. Then it works.
          
https://pay.instamed.com/Content/Js/Responsive/SupportedBrowsers.html
          
          
          
          
          I AM using one of those browsers!
          
          
          
          
        
    On 4/21/18 5:49 PM, Rebel wrote:
    
    
      
      Just found it - gotta hold the Settings
        button down. Attached.
        
        
        
        
      
      On 4/21/18 5:46 PM, Rebel wrote:
      
      
        
        Oh, evidently submitting
            feedback from the menu doesn't include them either.
          
          I don't see a Backup button anywhere in
            the Settings tabs.
          
          
          
          
        
        On 4/21/18 5:41 PM, Rebel wrote:
        
        
          
          I used the "send an email instead" link
            which placed that info inside an email.
            
            I assumed that was what you needed. There's
              no indication that sending an email does not include the anonymous settings and console
              messages.
                
                I'll send 'em following this.
              
            
          
          On 4/21/18 5:31 PM, Travis Roman
            [Masked] wrote:
          
          
            
               Preview: For privacy
                reasons, your rules are not included when you exp
                This email is forwarded from a MASKED EMAIL you created
                using Blur.
                IF THIS IS SPAM, CLICK HERE TO
                  BLOCK.
                
                Want to shop safely and privately online? Get Blur Premium. 
            
            
            For privacy reasons, your rules are not included when you
              export your settings. If you do want to send those, you'll
              have to create a backup via the Settings menu > Backup
              and export that.
            —
              You are receiving this because you authored the thread.
              Reply to this email directly, view it on GitHub, or mute the thread.
            
              
                
                
              
              
            
            {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/infernoboy/JavaScript-Blocker-5","title":"infernoboy/JavaScript-Blocker-5","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/infernoboy/JavaScript-Blocker-5"}},"updates":{"snippets":[{"icon":"PERSON","message":"@infernoboy in #27: For privacy reasons, your rules are not included when you export your settings. If you do want to send those, you'll have to create a backup via the Settings menu \u003e Backup and export that."}],"action":{"name":"View Issue","url":"https://github.com/infernoboy/JavaScript-Blocker-5/issues/27#issuecomment-383343894"}}}

**Comment by infernoboy** [comment]
That website works just fine too. And you never did attach your settings. Maybe you sent it through email, but GitHub doesn't include those attachments.

**Comment by GitTheHellOutaHere** [comment]
First you said "For privacy reasons, your
        rules are not included when you export your settings. If you do
        want to send those, you'll have to create a backup via the
        Settings menu > Backup and export that."
      So I
        did that
        and attached it to one of the emails sent 2 days ago.
        
      
        Then you asked me to send a copy of my settings by opening JSB and
        clicking Menu > Submit Feedback.
    I also did that 2 days ago.
      
    
      I didn't realize these emails were being
        posted on GitHub - I thought I was replying directly to
          you.
          You need to make that clear in the
            future in case someone does
              include privacy settings they don't want revealed to the public.
                
                So, if if Settings>Menu
                  doesn't work and Menu>Submit Feedback doesn't work,
                  what I'm I supposed to do? You're the one who said to do it
                  that way.
                
      
    
    On 4/24/18 11:44 AM, Travis Roman
      [Masked] wrote:
    
    
      
      That website works just fine too. And you never did attach your
        settings. Maybe you sent it through email, but GitHub doesn't
        include those attachments.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/infernoboy/JavaScript-Blocker-5","title":"infernoboy/JavaScript-Blocker-5","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/infernoboy/JavaScript-Blocker-5"}},"updates":{"snippets":[{"icon":"PERSON","message":"@infernoboy in #27: That website works just fine too. And you never did attach your settings. Maybe you sent it through email, but GitHub doesn't include those attachments."}],"action":{"name":"View Issue","url":"https://github.com/infernoboy/JavaScript-Blocker-5/issues/27#issuecomment-384038448"}}}

**Comment by infernoboy** [comment]
You created this GitHub issue… That's how GitHub works: you're replying to GitHub, not me. Nothing you attach to the emails will get sent. Either way, your original issue is not an issue with JS Blocker itself and the GitHub issue has been closed.
