### ISSUE TITLE
Safari 12 permanently disables Safari Extensions

### ISSUE THREAD

**Issue by creedflan738** [infernoboy/JavaScript-Blocker-5#29]
[What's new in Safari 12:](https://developer.apple.com/safari/whats-new/)
> Support for developer-signed .safariextz Safari Extensions in Safari 12 on macOS has been removed. They no longer appear in Safari preferences and cannot be enabled. On first launch users will receive a warning notification and these extension will not load.

Starting this fall, only the new style Safari App Extensions will be supported.

Hopefully this doesn't necessitate a total rewrite, or kill JSBlocker completely. Safari 12's "Intelligent Tracking Protection 2.0" lacks canvas fingerprinting detection & blocking, so it will be a huge step backwards, even with the other improvements.

**Comment by infernoboy** [comment]
I am aware of this. I have no experience creating native mac apps; it will therefore be impossible for me to re-create JSB as one as it does require a full rewrite in a language I do not know (Swift).

**Comment by daslicht** [comment]
how about this: 
https://georgegarside.com/blog/macos/install-any-safari-extension-macos-mojave/

?

**Comment by daslicht** [comment]
https://developer.apple.com/documentation/safariservices/safari_app_extensions/converting_a_legacy_safari_extension_to_a_safari_app_extension

what about this ?

**Comment by infernoboy** [comment]
Not happening.

**Comment by daslicht** [comment]
That's sad :(
anyone know's an alternative script blocker for Safari 12 ?

**Comment by IOOI-SqAR** [comment]
You can learn this. Swift is not that difficult. Also see https://developer.apple.com/documentation/safariextensions

**Comment by infernoboy** [comment]
I am fully aware of how to go about doing it, but key functions that make JSB possible are being removed. One important one being the canLoad event. Without it, JSB just wouldn't be able to function the way it does now. Only "content blockers" will work. The amount of work that will go into a rewrite that's nothing like the original is pointless in my view. It'd just be another content blocker you can get from any number of extensions. I am sorry to say unless Apple goes back and keeps the canLoad event, JSB won't ever exist as a Swift app.

**Comment by Tom012** [comment]
You can use Objective-C.
I don't use Swift neither.

**Comment by daslicht** [comment]
> It'd just be another content blocker 
I haven't found _any_ content blocker for safari 12 which lets you selectively block JavaScripts. Heck there isnt even a AdBlocker which lets you select which elements to block.

**Comment by infernoboy** [comment]
That's what I mean: the new style of extensions just don't have the capability to selectively allow/block items. Apple is set on their belief that doing so slows down page loading enough to warrant not allowing it altogether.

**Comment by daslicht** [comment]
Is there a way to display at least a list of scripts att least and let tham manually add to the app ?

**Comment by infernoboy** [comment]
Probably, but I will not be looking into this. Not going to recreate JSB as an inferior product.

**Comment by daslicht** [comment]
Hopefully there will be an alternative some say, until then I switch to firefox
