### ISSUE TITLE
Environmental information is not randomized

### ISSUE THREAD

**Issue by yxeri** [infernoboy/JavaScript-Blocker-5#3]
The same information is generated each time you turn it on and is not randomized on start of the plugin or between sites. In the source it looks like the information is hard coded and not randomized. This doesn't really protect against tracking (unless a lot of people have that feature on, but then you still have the unique IP...).

Good way to test it: https://panopticlick.eff.org

**Comment by infernoboy** [comment]
The reason I didn't bother randomizing browser information is because that info can be sent to the server regardless of what the JS value is. I will randomize it in JS, though, for the next release, along with window.screen and getTimezoneOffset.
