### ISSUE TITLE
Safari 12 - "Safari can't install this extension"

### ISSUE THREAD

**Issue by ylluminate** [infernoboy/JavaScript-Blocker-5#31]
Mourning the situation with Safari 12 presently.  When I start up and randomly during usage, I'll get this:
![popup](https://cl.ly/b5d85c4dd6f2/Image%202018-08-25%20at%202.31.57%20PM.png)

Any ideas as to how to address this yet?

**Comment by infernoboy** [comment]
No idea. It must be related to Safari, though, not the extension; I'm getting that message with others. JS Blocker remains installed despite the pop-up.
