### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by angrest** [infernoboy/JavaScript-Blocker-5#5]
since a couple of days, the blocker crashes on my machine:
In the log, I see the message
`20:19:42 MEZ /js/global/commands.js - 194
20:19:42 MEZ TypeError: resource.canLoad is not a function. (In 'resource.canLoad()', 'resource.canLoad' is undefined) - /js/global/commands.js - 695
Stack: /js/global/commands.js:695:88
20:19:42 MEZ /js/global/commands.js - 194`

It seems that the blocker is stuck in updating the filter lists.

The blocker then does no longer block ads nor scripts.
My computer runs on 10.11.3 (15D21), Safari is 9.0.3 (11601.4.4)

**Comment by angrest** [comment]
Problem persists. 
now 10.11.4, Safari 9.1 and JS Blocker 5.0.18

**Comment by infernoboy** [comment]
Have you tried to uninstall and reinstall? This causes all the settings to reset.

**Comment by angrest** [comment]
yes, I did. Interestingly enough, the settings survived the uninstall. 
Can I remove things manually?
regards
Axel

**Comment by infernoboy** [comment]
Settings can be restored to defaults from the Settings menu.

**Comment by angrest** [comment]
Solved by deleting the local data store of jsblock (survives uninstalling the plugin).
