### ISSUE TITLE
Unable to completely block ads and tracking

### ISSUE THREAD

**Issue by giveup** [infernoboy/JavaScript-Blocker-5#6]
uBlock orig VS jsb5
ublock orig block 3 elements
jsb is zero
Use same filter 
Test page:
https://github.com/infernoboy/JavaScript-Blocker-5/issues/new

**Comment by infernoboy** [comment]
uBlock origin does not exist for Safari. Using uBlock on Safari doesn't block anything either; it has the same exact limitations that JSB does due to Safari.

**Comment by bpinto** [comment]
@infernoboy I have a question if you could answer me. Does Safari (10) still limits what can be accomplished by an extension? Or can we already have the same blocking abilities as the other tools uBlock Origin for instance on other browsers.

**Comment by infernoboy** [comment]
Which blocking abilities of uBlock Origin are missing from JS Blocker?

**Comment by bpinto** [comment]
I was referring to the limitations you mentioned yourself:
> Using uBlock on Safari doesn't block anything either; it has the same exact limitations that JSB does due to Safari.

I could be wrong here, but I thought I had read that the Safari content blocker would only allow simple host blocks.

**Comment by infernoboy** [comment]
I don't even remember what the original issue was referring to at this point so I can't say what I meant by that, sorry.
