### ISSUE TITLE
Can't delete custom rules

### ISSUE THREAD

**Issue by bjartskular** [infernoboy/JavaScript-Blocker-5#7]
When I create a custom rule for a page from the page tab, I cannot delete it from the rules page. I can click the delete button to the right of the rule and the delete button will light up like its trying to do something, but after a few seconds the button will go back to the way it was before and the rule will remain.

I am running Safari 9.1 (11601.5.17.1) and JS Blocker 5.1.0

**Comment by infernoboy** [comment]
You have to click delete twice. Once to make it turn red, again to confirm the deletion.

**Comment by bjartskular** [comment]
Thanks for letting me know!
